backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("car_wash.urls")),
    path('admin/', admin.site.urls),
]

backend/carWash/urls.py
from django.urls import path

from . import views

app_name = "carWash"
urlpatterns = [
    path("", views.indexView, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("add-car", views.addCar, name="addCar"),
    path("your-cars", views.yourCars, name="yourCars"),
    path("appointment", views.appointment, name="appointment"),
    path("your-appointments", views.yourAppointments, name="yourAppointments"),
]

backend/car_wash/urls.py
from django.urls import path

from . import views

app_name = "car_wash"
urlpatterns = [
    path("", views.index_view, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("add-car", views.add_car, name="add_car"),
    path("your-cars", views.your_cars, name="your_cars"),
    path("appointment", views.appointment, name="appointment"),
    path("choose-time", views.choose_time, name="choose_time"),
    path("make-appointment", views.make_appointment, name="make_appointment"),
    path("your-appointments", views.your_appointments, name="your_appointments"),
]

backend/car_wash/models.py
from django.db import models
from django.contrib.auth.models import User


class Car(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
    brand = models.CharField(max_length=200, blank=False)
    model = models.CharField(max_length=200, blank=False)
    type = models.CharField(max_length=200, blank=False)


class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
    date = models.DateTimeField("appointment date", blank=False)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, blank=False)

backend/carWash/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout, login
from django.utils import timezone
from .models import Car, Appointment


def indexView(request):
    context = {"logged_in": request.user.is_authenticated}

    return render(request, "carwash/index.html", context)

def yourAppointments(request):
    if request.POST:
       carModels = request.POST.getlist("model") 
       for model in carModels:
           Car.objects.filter(model=model).delete()
       context = {"logged_in": request.user.is_authenticated}
       return render(request, "carwash/index.html", context)
    else:
        appointments = Appointment.objects.filter(user=request.user)
        print(appointments)
        return render(request, "carwash/your-appointments.html", {"appointments": appointments})

def yourCars(request):
    if request.POST:
       carModels = request.POST.getlist("model") 
       for model in carModels:
           Car.objects.filter(model=model).delete()
       context = {"logged_in": request.user.is_authenticated}
       return render(request, "carwash/index.html", context)
    else:
        cars = Car.objects.filter(user=request.user)
        return render(request, "carwash/your-cars.html", {"cars": cars})


def appointment(request):
    if request.POST:
        date = request.POST.get("date")
        time = request.POST.get("time")
        model = request.POST.get("car")
        if not date or not time or not model:
            return render(
                request,
                "carwash/appointment.html",
                {"error_message": "Fill all the fields"},
            )
        car = Car.objects.get(model=model)
        appointment = Appointment(user=request.user, date=(date + " " + time), car=car)
        appointment.save()
        context = {"logged_in": request.user.is_authenticated}
        return render(request, "carwash/index.html", context)
    else:
        cars = Car.objects.filter(user=request.user)
        print(timezone.now())
        return render(request, "carwash/appointment.html", {"cars": cars})


def addCar(request):
    if request.POST:
        brand = request.POST.get("brand")
        model = request.POST.get("model")
        type = request.POST.get("type")
        if not brand or not model or not type:
            return render(
                request, "carwash/car.html", {"error_message": "Fill all the fields"}
            )
        car = Car.objects.create(user=request.user, brand=brand, model=model, type=type)
        car.save()
        context = {"logged_in": request.user.is_authenticated}
        return render(request, "carwash/index.html", context)
    else:
        return render(request, "carwash/car.html", {})


def logout_view(request):
    logout(request)
    return render(request, "carwash/index.html", {})


def login_view(request):
    if request.POST:
        email = request.POST.get("email")
        password = request.POST.get("password")
        try:
            u = User.objects.get(email=email)
        except User.DoesNotExist:
            print("wrong")
            return render(
                request,
                "carwash/login.html",
                {"error_message": "Incorrect Email or Password"},
            )
        else:
            user = authenticate(username=u.username, password=password)
            if user is not None:
                login(request, user)
                context = {"logged_in": request.user.is_authenticated}
                return render(request, "carwash/index.html", context)
            else:
                return render(
                    request,
                    "carwash/login.html",
                    {"error_message": "Incorrect Email or Password"},
                )
    else:
        return render(request, "carwash/login.html", {})


def register(request):
    if request.POST:
        email = request.POST.get("email")
        userName = request.POST.get("username")
        password = request.POST.get("password")
        repeatPassword = request.POST.get("repeatPassword")
        print(email, userName, password, repeatPassword)
        if password != repeatPassword:
            return render(
                request,
                "carwash/register.html",
                {"error_message": "Passwords don't match"},
            )
        try:
            u = User.objects.get(email=email)
            isUsernameTaken = User.objects.filter(username=userName).exists()
            if isUsernameTaken:
                return render(
                    request,
                    "carwash/register.html",
                    {"error_message": "This Username is taken"},
                )
        except User.DoesNotExist:
            user = User.objects.create_user(
                username=userName, email=email, password=password
            )
            user.save()
            return render(request, "carwash/login.html", {})
        else:
            return render(
                request,
                "carwash/register.html",
                {"error_message": "User with this Email is already registered"},
            )
    else:
        return render(request, "carwash/register.html", {})

backend/car_wash/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout, login
from datetime import datetime
from .models import Car, Appointment


def index_view(request):
    context = {"logged_in": request.user.is_authenticated}
    return render(request, "car_wash/index.html", context)


def your_appointments(request):
    if request.POST:
        dates = request.POST.getlist("date")
        for date_str in dates:
            date = datetime.strptime(date_str, "%Y-%m-%d %H:%M")
            Appointment.objects.filter(date=date).delete()
        context = {"logged_in": request.user.is_authenticated}
        return render(request, "car_wash/index.html", context)
    else:
        appointments = Appointment.objects.filter(user=request.user)
        return render(
            request, "car_wash/your-appointments.html", {"appointments": appointments}
        )


def your_cars(request):
    if request.POST:
        car_models = request.POST.getlist("model")
        for model in car_models:
            Car.objects.filter(model=model).delete()
        context = {"logged_in": request.user.is_authenticated}
        return render(request, "car_wash/index.html", context)
    else:
        cars = Car.objects.filter(user=request.user)
        return render(request, "car_wash/your-cars.html", {"cars": cars})


def appointment(request):
    cars = Car.objects.filter(user=request.user)
    return render(request, "car_wash/appointment.html", {"cars": cars})


def choose_time(request):
    date = request.POST.get("date")

    request.session["date"] = date
    request.session["car_model"] = request.POST.get("car")

    starting_time = "8:30"
    current_hour = int(starting_time.split(":")[0])
    current_min = int(starting_time.split(":")[1])
    minute_increment = 30

    times = []

    while current_hour <= 17:
        current_min = int(current_min)
        if current_min == 0:
            current_min += minute_increment
        else:
            current_min = "00"
            current_hour += 1

        time_block = str(current_hour) + ":" + str(current_min)
        if Appointment.objects.filter(date=date + " " + time_block).exists():
            times.append("Reserved")
        else:
            times.append(time_block)

    return render(request, "car_wash/choose_time.html", {"times": times})


def make_appointment(request):
    date = request.session.get("date")
    car_model = request.session.get("car_model")
    time = request.POST.get("time")

    car = Car.objects.get(model=car_model)
    appointment = Appointment(user=request.user, date=(date + " " + time), car=car)
    appointment.save()
    del request.session["date"]
    del request.session["car_model"]

    context = {"logged_in": request.user.is_authenticated}
    return render(request, "car_wash/index.html", context)


def add_car(request):
    if request.POST:
        brand = request.POST.get("brand")
        model = request.POST.get("model")
        type = request.POST.get("type")
        if not brand or not model or not type:
            return render(
                request, "car_wash/car.html", {"error_message": "Fill all the fields"}
            )
        car = Car.objects.create(user=request.user, brand=brand, model=model, type=type)
        car.save()
        context = {"logged_in": request.user.is_authenticated}
        return render(request, "car_wash/index.html", context)
    else:
        return render(request, "car_wash/car.html", {})


def logout_view(request):
    logout(request)
    return render(request, "car_wash/index.html", {})


def login_view(request):
    if request.POST:
        email = request.POST.get("email")
        password = request.POST.get("password")
        try:
            u = User.objects.get(email=email)
        except User.DoesNotExist:
            return render(
                request,
                "car_wash/login.html",
                {"error_message": "Incorrect Email or Password"},
            )
        else:
            user = authenticate(username=u.username, password=password)
            if user is not None:
                login(request, user)
                context = {"logged_in": request.user.is_authenticated}
                return render(request, "car_wash/index.html", context)
            else:
                return render(
                    request,
                    "car_wash/login.html",
                    {"error_message": "Incorrect Email or Password"},
                )
    else:
        return render(request, "car_wash/login.html", {})


def register(request):
    if request.POST:
        email = request.POST.get("email")
        username = request.POST.get("username")
        password = request.POST.get("password")
        repeat_password = request.POST.get("repeatPassword")
        if password != repeat_password:
            return render(
                request,
                "car_wash/register.html",
                {"error_message": "Passwords don't match"},
            )
        try:
            u = User.objects.get(email=email)
            is_username_taken = User.objects.filter(username=username).exists()
            if is_username_taken:
                return render(
                    request,
                    "car_wash/register.html",
                    {"error_message": "This Username is taken"},
                )
        except User.DoesNotExist:
            user = User.objects.create_user(
                username=username, email=email, password=password
            )
            user.save()
            return render(request, "car_wash/login.html", {})
        else:
            return render(
                request,
                "car_wash/register.html",
                {"error_message": "User with this Email is already registered"},
            )
    else:
        return render(request, "car_wash/register.html", {})

backend/car_wash/templates/car_wash/appointment.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Appointment</title>
    <style>
      form {
        display: flex;
        flex-direction: column;
        width: 25%;
        gap: 6px;
        margin: auto;
      }
      p {
        width: 25%;
        margin: auto;
        margin-top: 6px;
      }
      .nav {
        width: 50%;
        display: flex;
        justify-content: space-between;
      }
    </style>
  </head>
  <body>
    <div class="nav">
      <h1><a href="{% url 'car_wash:index' %}">Home</a></h1>
      <h1>Make an appointment</h1>
    </div>
    <form action="{% url 'car_wash:choose_time' %}" method="post">
      {% csrf_token %}
      <label for="date">Date</label>
      <input
        type="date"
        name="date"
        value="2024-07-22"
        min="2024-01-01"
        max="2024-12-31"
        required
      />
      {% comment %} <label for="time">Time</label>
      <input
        type="time"
        name="time"
        min="09:00"
        max="18:00"
        step="1800"
        required
      />
      {% endcomment %}
      <select name="car">
        {% for car in cars %}
        <option value="{{car.model}}">{{car.brand}} {{car.model}}</option>
        {% endfor %}
      </select>
      {% if error_message %}
      <p><strong>{{error_message}} </strong></p>
      {%endif%}
      <button type="submit" style="width: 25%">Next</button>
    </form>
  </body>
</html>

backend/car_wash/templates/car_wash/car.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add your Car</title>
    <style>
      form {
        display: flex;
        flex-direction: column;
        width: 25%;
        gap: 6px;
        margin: auto;
      }

      p {
        width: 25%;
        margin: auto;
        margin-top: 6px;
      }
      .nav {
        width: 50%;
        display: flex;
        justify-content: space-between;
      }
    </style>
  </head>
  <body>
    <div class="nav">
      <h1><a href="{% url 'car_wash:index' %}">Home</a></h1>
      <h1>Add your Car</h1>
    </div>
    <form action="{% url 'car_wash:add_car' %}" method="post">
      {% csrf_token %}
      <label for="email">Brand</label>
      <input type="text" name="brand" />
      <label for="model">Model</label>
      <input type="text" name="model" />
      <label for="type">Type</label>
      <input type="text" name="type" />
      {% if error_message %}
      <p><strong>{{error_message}} </strong></p>
      {%endif%}
      <button type="submit" style="width: 25%">Add</button>
    </form>
  </body>
</html>

backend/car_wash/templates/car_wash/choose_time.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Choose Time</title>
  </head>
  <body>
    <form
      action="{% url 'car_wash:make_appointment' %}"
      method="post"
      style="width: 5%; margin: auto"
    >
      {% csrf_token %} {% for time in times %}
      <div style="display: flex; justify-content: space-between">
        {% if time == 'Reserved' %}
        <strong>{{time}}</strong>
        {% else %}
        <div>{{time}}</div>
        <input type="checkbox" name="time" value="{{time}}" />
        {% endif %}
      </div>
      {% endfor %}
      <button type="submit">Submit</button>
    </form>
  </body>
</html>

backend/car_wash/templates/car_wash/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CarWash</title>
  </head>
  <body>
    <h1>Welcome to my CarWash</h1>

    {% if not logged_in %}
    <button><a href="{% url 'car_wash:login' %}">Login</a></button>
    {% endif %} {% if logged_in %}
    <button><a href="{% url 'car_wash:logout' %}">Log out</a></button>
    <button><a href="{% url 'car_wash:add_car' %}">Add Car</a></button>
    <button>
      <a href="{% url 'car_wash:appointment' %}">Make an appointment</a>
    </button>
    <button>
      <a href="{% url 'car_wash:your_cars' %}">Your Cars</a>
    </button>
    <button>
      <a href="{% url 'car_wash:your_appointments' %}">Your Appointments</a>
    </button>
    {% endif %}
  </body>
</html>

backend/car_wash/templates/car_wash/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <style>
      form {
        display: flex;
        flex-direction: column;
        width: 25%;
        gap: 6px;
        margin: auto;
      }
      p {
        width: 25%;
        margin: auto;
        margin-top: 6px;
      }
      .nav {
        width: 50%;
        display: flex;
        justify-content: space-between;
      }
    </style>
  </head>
  <body>
    <div class="nav">
      <h1><a href="{% url 'car_wash:index' %}">Home</a></h1>
      <h1>Login</h1>
    </div>
    <form action="{% url 'car_wash:login' %}" method="post">
      {% csrf_token %}
      <label for="email">Email</label>
      <input type="text" name="email" />
      <label for="password">Password</label>
      <input type="password" name="password" />
      {% if error_message %}
      <p><strong>{{error_message}} </strong></p>
      {%endif%}
      <button type="submit" style="width: 25%">Submit</button>
    </form>

    <p>
      Don't have an account?
      <a href="{% url 'car_wash:register' %}">register</a>
    </p>
  </body>
</html>

backend/car_wash/templates/car_wash/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Register</title>
    <style>
      form {
        display: flex;
        flex-direction: column;
        width: 25%;
        gap: 6px;
        margin: auto;
      }

      p {
        width: 25%;
        margin: auto;
        margin-top: 6px;
      }
      .nav {
        width: 50%;
        display: flex;
        justify-content: space-between;
      }
    </style>
  </head>
  <body>
    <div class="nav">
      <h1><a href="{% url 'car_wash:index' %}">Home</a></h1>
      <h1>Register</h1>
    </div>
    <form action="{% url 'car_wash:register' %}" method="post">
      {% csrf_token %}
      <label for="email">Email</label>
      <input type="text" name="email" />
      <label for="username">Username</label>
      <input type="text" name="username" />
      <label for="password">Password</label>
      <input type="password" name="password" />
      <label for="repeatPassword">Repeat Password</label>
      <input type="password" name="repeatPassword" />
      {% if error_message %}
      <p><strong>{{error_message}} </strong></p>
      {%endif%}
      <button type="submit" style="width: 25%">Submit</button>
    </form>

    <p>Already registered? <a href="{% url 'car_wash:login' %}">login</a></p>
  </body>
</html>

backend/car_wash/templates/car_wash/your-appointments.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Your cars</title>
    <style>
      .nav {
        width: 50%;
        display: flex;
        justify-content: space-between;
      }
    </style>
  </head>
  <body>
    <div class="nav">
      <h1><a href="{% url 'car_wash:index' %}">Home</a></h1>
      <h1>Your Appointments</h1>
    </div>
    <form
      action="{% url 'car_wash:your_appointments' %}"
      method="post"
      style="
        display: flex;
        flex-direction: column;
        gap: 4px;
        width: 15%;
        margin: auto;
      "
    >
      {% csrf_token %} {% for appointment in appointments %}
      <div style="display: flex; justify-content: space-between">
        <div>
          {{appointment.car.brand}} {{appointment.car.model}},
          {{appointment.date}}
        </div>
        <input type="checkbox" name="date" value="{{appointment.date|date:"Y-m-d H:i"}}" />
      </div>
      {% endfor %}
      <button type="submit">Delete selected</button>
    </form>
  </body>
</html>

backend/car_wash/templates/car_wash/your-cars.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Your cars</title>
    <style>
      .nav {
        width: 50%;
        display: flex;
        justify-content: space-between;
      }
    </style>
  </head>
  <body>
    <div class="nav">
      <h1><a href="{% url 'car_wash:index' %}">Home</a></h1>
      <h1>Your Cars</h1>
    </div>
    <form
      action="{% url 'car_wash:your_cars' %}"
      method="post"
      style="
        display: flex;
        flex-direction: column;
        gap: 4px;
        width: 15%;
        margin: auto;
      "
    >
      {% csrf_token %} {% for car in cars %}
      <div style="display: flex; justify-content: space-between">
        <div>{{car.brand}} {{car.model}}</div>
        <input type="checkbox" name="model" value="{{car.model}}" />
      </div>
      {% endfor %}
      <button type="submit">Delete selected</button>
    </form>
  </body>
</html>